ALTER TABLE economy ADD COLUMN bank TEXT NOT NULL DEFAULT '0';
ALTER TABLE economy ADD COLUMN bankCapacity TEXT NOT NULL DEFAULT '100000';

CREATE TABLE IF NOT EXISTS inventory (
  userId TEXT NOT NULL,
  itemId TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (userId, itemId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_inventory_userId ON inventory(userId);
